cache_dir:
  result_dir: 'results'

api_config:

  lunar-gpt-4o-mini:
    api_key: "your-azure-openai-api-key"
    azure_endpoint: "https://lunarchatgpt.openai.azure.com/"
    version: "2024-10-21"
    model_name: "lunar-gpt-4o-mini"

  lunar-deepseek-r1: 
    api_key: "your-azure-openai-api-key"
    azure_endpoint: "https://ai-mdanilo1101ai528062209347.services.ai.azure.com/"
    version: "2024-05-01-preview"
    model_name: "lunar-deepseek-r1"

  lunar-gpt-4o: 
    api_key: "your-azure-openai-api-key"
    azure_endpoint: "https://ai-mdanilo1101ai528062209347.openai.azure.com/"
    version: "2024-12-01-preview"
    model_name: "gpt-4o"
  
  gemini:
    api_key: "your-gemini-api-key-here"

data_dir:
  part1: "data/data.json"
  part2: "data/data_2.json"






